workflows:
  android-workflow:
    name: WIFE Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.example.wife"
      android_signing:
        - keystore_reference: null
      groups:
        - android
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
