workflows:
  android-workflow:
    name: WIFE Android Debug Build
    max_build_duration: 60
    environment:
      groups:
        - android
    scripts:
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
