workflows:
  android-apk:
    name: WIFE APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      groups:
        - android
    scripts:
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
